language: python
python:
  # Disabled Temporarily in order to test setup
  #- "3.3"
  #- "3.4"
  #- "3.5"
  - "3.6"
  #- "3.6-dev"
  #- "3.7-dev"
before_install:
  - sudo apt-get install graphviz libgraphviz-dev -y
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - python -m unittest discover -s "$(pwd)/tests" -t "$(pwd)"
#deploy:
#  provider: pypi
#  user: "Your username"
#  password:
#    secure: ""
#  on:
#    branch: master
#    tags: true